data<-read.table("household_power_consumption.txt", header=TRUE,sep=";", na.strings="?",colClasses=c(rep("character",2),rep("numeric",3),"NULL",rep("numeric",3)))
tdata <- subset(data,Date %in% c("2/1/2007","2/2/2007"))
tdata$datetime <- strptime(paste(tdata$Date,tdata$Time,sep=" "),format='%m/%d/%Y %H:%M:%S')
par(mar=c(4.1,5.1,4.1,2.1))
par(mfcol=c(2,2))
plot(tdata$datetime,tdata$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(tdata$datetime,tdata$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering",ylim=c(0,28))
lines(metering$datetime,metering$Sub_metering_2,type="l",col="red")
lines(metering$datetime,metering$Sub_metering_3,type="l",col="blue")
legend("topright",c("Sub_metering_1         ","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"),y.intersp=1.7,bty='n')
plot(tdata$datetime,tdata$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(tdata$datetime,tdata$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.copy(device=png,file="plot4.png",width=480,height=480)
dev.off()
