data<-read.table("household_power_consumption.txt", header=TRUE,sep=";", na.strings="?",colClasses=c(rep("character",2),rep("NULL",4),rep("numeric",3)))
metering <- subset(data,Date %in% c("2/1/2007","2/2/2007"))
metering$datetime <- strptime(paste(metering$Date,metering$Time,sep=" "),format='%m/%d/%Y %H:%M:%S')
par(mar=c(4.1,5.1,4.1,2.1))
with(metering,plot(datetime,Sub_metering_1,type="l",xlab="",ylab="Energy sub metering",ylim=c(0,23)))
lines(metering$datetime,metering$Sub_metering_2,type="l",col="red")
lines(metering$datetime,metering$Sub_metering_3,type="l",col="blue")
legend("topright",c("Sub_metering_1         ","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"),y.intersp=1.7)
dev.copy(device=png,file="plot3.png",width=480,height=480)
dev.off()
